before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: NyBt+6FlBHhPjicjBVDU6+8Tq2W8qY5NsI4HAr0UTQbZ6svO/AaXeD95rymDuiGrENB0YG/uc1RTL7J4+8+ZGSbTe5eMg1Wl8EyCZS3lTojytgpWYjab4uWsH3Wa5hTCeEfnrqTxtJsMCUkE/HNm2qV2G86IuIX2tCXUXI3FEYK/q4xE5PuucanA4KI5lrfvUOc2yhakRmpEoJTtZiT6ewH0BrbcT7NSJFvfOpiWMNsuOIEc+a8b1SIzbxImeuJAwJzHWPvHY14eg+/q1NQh7EnGwd7gcn8W2UCQEz8gvCDTJmRXRcfE96kPJubuSrd2kEyiHYlRZQZLwzqxkw/Cj94rpUcj2VsZF1kC1LNM7I/wbObPeylmxmrXGBPIAALYkr3+hBjyj/VKGgKyFmX1zs++tMuz8kku6v04Y2/xztCyggU2q6AiuoFbXXp9bfwi25b2XyxdPD0JSsaKebpwV36Cjy8WoeOppgeKvgCpB49nsVL2cPvoEQjljGxjM1DS4LQiL75Ey48Ux7jOAxwJz0CC9IijgsK6jq+zbxQXOAJzFWSfP0IJNqkx+H8VqQW3eePt0cQn699Iqk0va9GtDPqGoPE7FvZV0Jq42x9OBVKT5V22jD+/8topZsnHITw2tQSAdvKJMVW/g4vZdB8qQ7nMoCGQD1KEEyxs9AVy8JU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
